baseurl      = ""
title        = "Zachary Taylor"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "Zachary Taylor"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Computer Science, Cyber Security, and Math Student"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My home page and blog."
  keywords = "zach, taylor, zach taylor, cybersecurity"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Zachary D. Taylor"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    #readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/zach"
      logoHomeLink = ""
    # or
    #
    # path = ""
    # alt = ""

  # And you can even create generic menu
  [menu]
    [[menu.main]]
      identifier = "resume"
      name       = "Resume"
      url        = "/resume.pdf"

    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"

  [[params.social]]
    name = "github"
    url = "https://github.com/taylozac"

  [[params.social]]
    name = "discord"
    url = "https://discord.com/users/199396039357104128"

  [[params.social]]
    name = "email"
    url = "mailto:taylozac@oregonstate.edu?subject=Mail from zach-t.com"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/Toxic_Z_"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/zachary-taylor-726a31169/"
